name: Deploy Release

on:
  release:
    types:
      - created
env:
  PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare

      - name: Deploy
        run: dart compile exe bin/main.dart -o supagen

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./supagen
          asset_name: supagen
          asset_content_type: application/octet-stream
