name: Deploy Release

on:
  release:
    types:
    - created
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare environment
      uses: ./.github/actions/prepare

    - name: Deploy
      run: dart compile exe bin/dart_github_workflow.dart -o dart_github_workflow

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dart_github_workflow
        asset_name: dart_github_workflow
        asset_content_type: application/octet-stream
